[package]
name = "sprite_animation"
version = "0.1.0"
authors = ["PhaestusFox <phaestusfox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
ron = "0.6.4"
serde = "*"